scrape_configs:
  - job_name: 'app-metrics'
    metrics_path: '/actuator/prometheus'
    # cứ 5 giây, Prometheus server sẽ thu thập metrics từ endpoint
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']